safe: false
source: .
destination: ./_site
plugins_dir: ./_plugins
lsi: true
highlighter: rouge
markdown: kramdown
exclude: ['_DOCS', '_SCRIPTS', '.travis.yml', '.travis.d', '.sass-cache', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'LICENSE.md']
sass:
  style: compressed
encoding: UTF-8

url: http://conferences.sigcomm.org
baseurl: /sigcomm/2017

# Configuration for site
title: ACM SIGCOMM 2017
logo:
  image: images/sigcomm-2017-logo.png
  info: ACM SIGCOMM 2017, Los Angeles, CA

google_analytics_id: UA-83529610-1

program:
  # If the specified file doesn't exist, there will be command-line dialog to create it 
  google_client_id: .travis.d/google_client_id.json
  # Google spreadsheet with the conference data
  spreadsheet: 1J-lppI-_qcclJbmP3DN_xhgKnJnL6S344BUQQ9JbvIE

# Configuration for navbar.html
menu:
- name: Home
  url: /
  icon: fa-home
- name: Supporters
  url: /supporters.html
  icon: fa-handshake-o
- name: Conference
  icon: fa-bar-chart
  submenu:
    # - name: Program
    #   url: /program.html
    # - name: Awards
    #   url: /awards.html
    - name: Social Events
      url: /social-events.html
- name: Program Committee
  url: /tpc.html
  icon: fa-users
    # - name: Posters
    #   url: /posters.html
    # - name: Demos
    #   url: /demos.html
    # - name: ACM SRC
    #   url: /acm-src.html
    # - name: Industrial Demos
    #   url: /industrial-demos.html
    # - name: Posters/Demos from Main Track
    #   url: /posters-and-demos-main-track.html
    # - name: Topic Preview
    #   url: /topic-preview.html
    # - name: Mentoring
    #   url: /mentoring.html
- name: Workshops
  icon: fa-bullhorn
  submenu:
    - name: MECOMM
      url: /workshop-mecomm.html
    - name: MobiArch
      url: /workshop-mobiarch.html
    - name: KBNets
      url: /workshop-kbnets.html
    - name: Big-DAMA
      url: /workshop-big-dama.html
    - name: Internet QoE
      url: /workshop-internet-qoe.html
    - name: HotConNet
      url: /workshop-hotconnet.html
    - name: Reproducibility
      url: /workshop-reproducibility.html
    - name: VR/AR Network
      url: /workshop-vrar-network.html
    - name: NetPL
      url: /workshop-netpl.html
    - name: N2Women
      url: /workshop-n2women.html
# - name: Tutorials
#   submenu:
#     - name: TBD
#       url: /tbd2.html
# - name: Registration
#   url: /registration.html
- name: Local Information
  icon: fa-map
  submenu:
    - name: Venue
      url: /venue.html
    - name: Accommodations
      url: /accommodations.html
    - name: Visa Information
      url: /visa.html
    - name: Tourism
      url: /tourism.html
    # - name: Room Share
    #   url: /room-share.html
    # - name: Travel Grants
    #   url: /travel-grants.html
    # - name: N2Women Fellowship
    #   url: /n2women-fellowship.html
    # - name: N2Women Travel Grant
    #   url: /n2women-travel-grant.html
- name: Organizing Committee
  url: /org-committee.html
  icon: fa-users
- name: Calls
  icon: fa-bullhorn
  submenu:
    - name: Call for Papers
      url: /cfp.html
    - name: Submission Requirements
      url: /submission.html
    - name: Call for Posters & Demos
      url: /cf-posters.html
    - name: Student Research Competition
      url: /src.html
    # - name: Call for Industrial Demos
    #   url: /cf-industrial-demos.html
    - name: Call for Tutorials
      url: /cf-tutorials.html
    # - name: Call for Workshops
    #   url: /cf-workshops.html
- name: Policies
  icon: fa-book
  submenu:
    - name: Author Registration Policy
      url: /policy-author-registration.html
    - name: Anti-Harassment Policy
      url: /policy-anti-harassment.html

colors:
  highlight: 2E85C2
  highlight-darker: 2E85C2
  hfont: F9E90C

  program:
    break-background: d1d1d1
